# Generated by Django 3.2.6 on 2021-08-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementadmin', '0002_auto_20210808_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_company',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
